outlines:
    default: { width: 28, height: 30 }
    action:  { width: 28, height: 30 }
    altline: { width: 42, height: 30 }
    wide:    { width: 42, height: 30 }
    spaceline: { width: 112, height: 30 }
    special: { width: 28, height: 30 }
    small:   { width: 42, height: 30 }
    blank:   { width: 14, height: 30 }

views:
    base:
        - "Tab - 1 2 3 4 5 6 7 8 9 0"
        - "Del + q w e r t y u i o p"
        - "Menu blank \" a s d f g h j k l blank"
        - "Shift_L blank preferences z x c v b n m / BackSpace"
        - "show_numbers Ctrl Alt , space period  blank Return"
    upper:
        - "M1 _ ! @ # $ % ^ & * ( )"
        - "M3 = Q W E R T Y U I O P"
        - "M4 blank ' A S D F G H J K L blank"
        - "Shift_L blank preferences Z X C V B N M \\ BackSpace"
        - "show_actions M2 M5 colon space ? blank Return"
    numbers:
        - "Esc M1 # { } \\ / * - ( ) blank"
        - "Del M3 ! [ ] 7 8 9 + $ | blank"
        - "Home M4 ^ < > 4 5 6 = % ' blank"
        - "End M2 _ ; ~ 1 2 3 ↑ , BackSpace"
        - "show_letters M5 blank colon period space_small 0 ← ↓ → Return"
    actions:
        - "Tab PgUp blank F1  F2  F3  F4  F5  F6"
        - "Del PgDn blank F7 F8 F9  F10 F11 F12"
        - "Menu Home blank M1  M2  M3  M4  M5  M6"
        - "show_numbers End blank M7  M8  M9  M10 M11 BackSpace"
        - "show_letters Ctrl Alt , space M12 Return"

buttons:
    Shift_L:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "altline"
        icon: "key-shift"
    BackSpace:
        outline: "altline"
        icon: "edit-clear-symbolic"
        action: erase
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "small"
        label: "123"
    show_numbers_from_symbols:
        action:
            set_view: "numbers"
        outline: "small"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "small"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "small"
        label: "SYB"
    show_actions:
        action:
            set_view: "actions"
        outline: "small"
        label: "ACT"
    period:
        outline: "default"
        text: "."
    space:
        outline: "spaceline"
        text: " "
    space_small:
        outline: "small"
        text: " "
    blank:
        outline: "blank"
        text: ""
    Return:
        outline: "small"
        icon: "key-enter"
        keysym: "Return"
    colon:
        text: ":"
    M1:
        outline: "small"
        text: "Heading Home"
        label: "Head"
    M2:
        outline: "small"
        text: "I got your text, thank you"
        label: "I got"
    M3:
        outline: "small"
        text: "name@hotmail.com"
        label: "Hotm"
    M4:
        outline: "small"
        text: "name@gmail.com"
        label: "Gmai"
    M5:
        outline: "small"
        text: "M5"
        label: "M5"
    M6:
        outline: "small"
        text: "am"
        label: "am"
    M7:
        outline: "small"
        text: "pm"
        label: "pm"
    M8:
        outline: "small"
        text: "M8"
        label: "M8"
    M9:
        outline: "small"
        text: "M9"
        label: "M9"
    M10:
        outline: "small"
        text: "M10"
        label: "M10"
    M11:
        outline: "small"
        text: "M11"
        label: "M11"
    M12:
        outline: "small"
        text: "M12"
        label: "M12"
    F1:
        outline: "small"
        keysym: "F1"
    F2:
        outline: "small"
        keysym: "F2"
    F3:
        outline: "small"
        keysym: "F3"
    F4:
        outline: "small"
        keysym: "F4"
    F5:
        outline: "small"
        keysym: "F5"
    F6:
        outline: "small"
        keysym: "F6"
    F7:
        outline: "small"
        keysym: "F7"
    F8:
        outline: "small"
        keysym: "F8"
    F9:
        outline: "small"
        keysym: "F9"
    F10:
        outline: "small"
        keysym: "F10"
    F11:
        outline: "small"
        keysym: "F11"
    F12:
        outline: "small"
        keysym: "F12"
    Esc:
        outline: "small"
        keysym: "Escape"
    Tab:
        outline: "small"
        keysym: "Tab"
    Del:
        outline: "small"
        keysym: "Delete"
    Insert:
        outline: "action"
        keysym: "Insert"
    Menu:
        outline: "small"
        keysym: "Menu"
    Pause:
        outline: "action"
        keysym: "Pause"
    Break:
        outline: "action"
        keysym: "Break"
    Home:
        outline: "small"
        keysym: "Home"
    End:
        outline: "small"
        keysym: "End"
    PgUp:
        outline: "small"
        keysym: "Page_Up"
    PgDn:
        outline: "small"
        keysym: "Page_Down"
    "↑":
        outline: "default"
        keysym: "Up"
    "↓":
        outline: "default"
        keysym: "Down"
    "←":
        outline: "default"
        keysym: "Left"
    "→":
        outline: "default"
        keysym: "Right"
    Up:
        label: "↑"
        outline: "action"
        keysym: "Up"
    Left:
        label: "←"
        outline: "action"
        keysym: "Left"
    Down:
        label: "↓"
        outline: "action"
        keysym: "Down"
    Right:
        label: "→"
        outline: "action"
        keysym: "Right"
    Ctrl:
        modifier: "Control"
        outline: "small"
        label: "Ctrl"
    Alt:
        modifier: "Alt"
        outline: "small"
        label: "Alt"
