outlines:
    default: { width: 30, height: 38 }
    action:  { width: 30, height: 38 }
    altline: { width: 45, height: 38 }
    wide:    { width: 45, height: 38 }
    spaceline: { width: 90, height: 38 }
    special: { width: 30, height: 38 }
    small:   { width: 45, height: 38 }
    blank:   { width: 15, height: 38 }

views:
    base:
        - "Tab q w e r t y u i o p"
        - "Menu blank a s d f g h j k l blank"
        - "Shift_L \" z x c v b n m blank BackSpace"
        - "show_numbers Ctrl - , space period preferences Return"
    upper:
        - "M1 Q W E R T Y U I O P"
        - "M3 blank A S D F G H J K L blank"
        - "Shift_L ' Z X C V B N M blank BackSpace"
        - "show_actions blank colon + ; space ? ! Return"
    numbers:
        - "Esc blank ~ | * $ 7 8 9 - Del"
        - "Home blank ^ \\ / % 4 5 6 + space_small"
        - "End blank < > ↑ blank 1 2 3 = BackSpace"
        - "show_letters colon ← ↓ → 0 period , Return"
    actions:
        - "Del ( F1  F2  F3  F4  F5  F6"
        - "Menu ) F7 F8 F9  F10 F11 F12"
        - "show_numbers [ M1 M5 M6 M7 M8 BackSpace"
        - "show_letters ] M3 M9 M10 M11 M12 Return"

buttons:
    Shift_L:
        action:
            locking:
                lock_view: "upper" 
                unlock_view: "base"
        outline: "altline"
        icon: "key-shift"
    BackSpace:
        outline: "altline"
        icon: "edit-clear-symbolic"
        action: erase
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "small"
        label: "123"
    show_numbers_from_symbols:
        action:
            set_view: "numbers"
        outline: "small"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "small"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "small"
        label: "SYB"
    show_actions:
        action:
            set_view: "actions"
        outline: "small"
        label: "ACT"
    period:
        outline: "default"
        text: "."
    space:
        outline: "spaceline"
        text: " "
    space_small:
        outline: "small"
        text: " "
    blank:
        outline: "blank"
        text: ""
    Return:
        outline: "small"
        icon: "key-enter"
        keysym: "Return"
    colon:
        text: ":"
    M1:
        outline: "small"
        text: "Heading Home"
        label: "Head"
    M2:
        outline: "small"
        text: "M2"
        label: "M2"
    M3:
        outline: "small"
        text: "OK, Thank You!"
        label: "OK,"
    M4:
        outline: "small"
        text: "M4"
        label: "M4"
    M5:
        outline: "small"
        text: "M5"
        label: "M5"
    M6:
        outline: "small"
        text: "M6"
        label: "M6"
    M7:
        outline: "small"
        text: "M7"
        label: "M7"
    M8:
        outline: "small"
        text: "M8"
        label: "M8"
    M9:
        outline: "small"
        text: "M9"
        label: "M9"
    M10:
        outline: "small"
        text: "M10"
        label: "M10"
    M11:
        outline: "small"
        text: "M11"
        label: "M11"
    M12:
        outline: "small"
        text: "M12"
        label: "M12"
    F1:
        outline: "small"
        keysym: "F1"
    F2:
        outline: "small"
        keysym: "F2"
    F3:
        outline: "small"
        keysym: "F3"
    F4:
        outline: "small"
        keysym: "F4"
    F5:
        outline: "small"
        keysym: "F5"
    F6:
        outline: "small"
        keysym: "F6"
    F7:
        outline: "small"
        keysym: "F7"
    F8:
        outline: "small"
        keysym: "F8"
    F9:
        outline: "small"
        keysym: "F9"
    F10:
        outline: "small"
        keysym: "F10"
    F11:
        outline: "small"
        keysym: "F11"
    F12:
        outline: "small"
        keysym: "F12"
    Esc:
        outline: "small"
        keysym: "Escape"
    Tab:
        outline: "small"
        keysym: "Tab"
    Del:
        outline: "small"
        keysym: "Delete"
    Insert:
        outline: "action"
        keysym: "Insert"
    Menu:
        outline: "small"
        keysym: "Menu"
    Pause:
        outline: "action"
        keysym: "Pause"
    Break:
        outline: "action"
        keysym: "Break"
    Home:
        outline: "small"
        keysym: "Home"
    End:
        outline: "small"
        keysym: "End"
    PgUp:
        outline: "small"
        keysym: "Page_Up"
    PgDn:
        outline: "small"
        keysym: "Page_Down"
    "↑":
        outline: "altline"
        keysym: "Up"
    "↓":
        outline: "altline"
        keysym: "Down"
    "←":
        outline: "altline"
        keysym: "Left"
    "→":
        outline: "altline"
        keysym: "Right"
    Up:
        label: "↑"
        outline: "action"
        keysym: "Up"
    Left:
        label: "←"
        outline: "action"
        keysym: "Left"
    Down:
        label: "↓"
        outline: "action"
        keysym: "Down"
    Right:
        label: "→"
        outline: "action"
        keysym: "Right"
    Ctrl:
        modifier: "Control"
        outline: "small"
        label: "Ctrl"
    Alt:
        modifier: "Alt"
        outline: "small"
        label: "Alt"
