---
outlines:
    default: { width: 45, height: 40 }
    action:  { width: 45,    height: 40 }
    altline: { width: 45, height: 40 }
    wide:    { width: 45, height: 40 }
    spaceline: { width: 180, height: 40 }
    blank:   { width: 15, height: 40 }
    blank2:  { width: 30, height: 40 }
    blank3:  { width: 45, height: 40 }
    special: { width: 45, height: 40 }
    small: { width: 45, height: 40 }

views:
    base:
        - "Esc q w e r t y u i o p ( ) BackSpace 7 8 9 -"
        - "Tab blank2 a s d f g h j k l ' Return blank Del 4 5 6 +"
        - "Shift_L Menu z x c v b n m , period Shift_L ↑ $ 1 2 3 *"
        - "show_actions Ctrl Alt preferences http space com ; ← ↓ → \\ 0 = /"
    upper:
        - "Esc Q W E R T Y U I O P [ ] BackSpace Home ↑ PgUp -"
        - "Tab blank2 A S D F G H J K L \"  Return blank Del ← blank3 → +"
        - "Shift_L Menu Z X C V B N M ! ? Shift_L ↑ @ End ↓ PgDn *"
        - "show_actions Ctrl Alt preferences blank3 space blank3 colon ← ↓ → < 0 = >"
    numbers:
        - "PgUp M1 [ ] 7 8 9 + - $ | ( )"
        - "PgDn M2 < > 4 5 6 = * % ' { }"
        - "Home M3 ~ ↑ 1 2 3 , / \\ colon ;"
        - "End M4 ← ↓ → 0 period BackSpace  Return show_letters"
    symbols:
        - "[ ] 7 8 9 + $ | PgDn Home"
        - "< > 4 5 6 = % ' PgUp End"
        - "~ ↑ 1 2 3 , colon \" "
        - "← ↓ → 0 period show_letters Return"
    actions:
        - "blank3 blank3 blank3 F1  F2  F3  F4  F5  F6  F7  F8  F9  F10 F11 F12 blank3 blank3 blank3"
        - "blank3 blank3 blank3 M1  M2  M3  M4  M5  M6  M7  M8  M9  M10 http com blank3 blank3 blank3"
        - "blank3 blank3 blank3 ~ ! @ # $ % ^ & * < > blank3 blank3 blank3 blank3"
        - "show_letters Menu Break Up Left Down Right blank3 blank3 blank3 blank3 blank3 blank3 blank3 blank3 blank3 blank3 blank3"

buttons:
    Shift_L:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "altline"
        icon: "key-shift"
    BackSpace:
        outline: "altline"
        icon: "edit-clear-symbolic"
        action: erase
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "wide"
        label: "123"
    show_numbers_from_symbols:
        action:
            set_view: "numbers"
        outline: "altline"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "small"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "small"
        label: "SYB"
    show_actions:
        action:
            set_view: "actions"
        outline: "altline"
        label: ">_"
    period:
        outline: "default"
        text: "."
    space:
        outline: "spaceline"
        text: " "
    blank:
        outline: "blank"
        text: ""
    blank2:
        outline: "blank2"
        text: ""
    blank3:
        outline: "blank3"
        text: ""
    Return:
        outline: "wide"
        icon: "key-enter"
        keysym: "Return"
    colon:
        text: ":"
    M1:
        outline: "small"
        text: "Heading Home"
        label: "Head"
    M2:
        outline: "small"
        text: "OK, thank you!"
        label: "OK"
    M3:
        outline: "small"
        text: "hotmail.com"
        label: "Hotm"
    M4:
        outline: "small"
        text: "gmail.com"
        label: "Gmai"
    M5:
        outline: "small"
        text: "Username"
        label: "User"
    M6:
        outline: "small"
        text: "Password"
        label: "Pass"
    M7:
        outline: "small"
        text: "123-456-7890"
        label: "ph#"
    M8:
        outline: "small"
        text: "Mem8"
        label: "Mem8"
    M9:
        outline: "small"
        text: "Mem9"
        label: "Mem9"
    M10:
        outline: "small"
        text: "Mem10"
        label: "Mem10"  
    http:
        outline: "small"
        text: "https://"
        label: "http" 
    com:
        outline: "small"
        text: ".com"
        label: ".com"
    F1:
        outline: "small"
        keysym: "F1"
    F2:
        outline: "small"
        keysym: "F2"
    F3:
        outline: "small"
        keysym: "F3"
    F4:
        outline: "small"
        keysym: "F4"
    F5:
        outline: "small"
        keysym: "F5"
    F6:
        outline: "small"
        keysym: "F6"
    F7:
        outline: "small"
        keysym: "F7"
    F8:
        outline: "small"
        keysym: "F8"
    F9:
        outline: "small"
        keysym: "F9"
    F10:
        outline: "small"
        keysym: "F10"
    F11:
        outline: "small"
        keysym: "F11"
    F12:
        outline: "small"
        keysym: "F12"
    Esc:
        outline: "small"
        keysym: "Escape"
    Tab:
        outline: "small"
        keysym: "Tab"
    Del:
        outline: "small"
        keysym: "Delete"
    Insert:
        outline: "small"
        keysym: "Insert"
    Menu:
        outline: "small"
        keysym: "Menu"
    Pause:
        outline: "action"
        keysym: "Pause"
    Break:
        outline: "small"
        keysym: "Break"
    Home:
        outline: "small"
        keysym: "Home"
    End:
        outline: "small"
        keysym: "End"
    PgUp:
        outline: "small"
        keysym: "Page_Up"
    PgDn:
        outline: "small"
        keysym: "Page_Down"
    "↑":
        outline: "default"
        keysym: "Up"
    "↓":
        outline: "default"
        keysym: "Down"
    "←":
        outline: "default"
        keysym: "Left"
    "→":
        outline: "default"
        keysym: "Right"
    Up:
        label: "↑"
        outline: "action"
        keysym: "Up"
    Left:
        label: "←"
        outline: "action"
        keysym: "Left"
    Down:
        label: "↓"
        outline: "action"
        keysym: "Down"
    Right:
        label: "→"
        outline: "action"
        keysym: "Right"
    Ctrl:
        modifier: "Control"
        outline: "small"
        label: "Ctrl"
    Alt:
        modifier: "Alt"
        outline: "small"
        label: "Alt"
