---
outlines:
    default: { width: 48, height: 42 }
    action:  { width: 48, height: 42 }
    altline: { width: 48, height: 42 }
    wide:    { width: 48, height: 42 }
    spaceline: { width: 96, height: 42 }
    def_13:   { width: 16, height: 42 }
    def_23:  { width: 32, height: 42 }
    special: { width: 48, height: 42 }
    small:   { width: 48, height: 42 }

views:
    base:
        - "Tab blank q w e r t s_| @ 7 8 9 - y u i o p Esc"
        - "Menu s_/ a s d f g blank # 4 5 6 + blank h j k l s_b Del "
        - "Shift_L preferences z x c v b * 1 2 3 ↑ b n m , period BackSpace"
        - "show_actions Ctrl Alt space s_( s_) s_< $ = 0 ← ↓ → space colon \" Return" 
    upper:
        - "Tab blank Q W E R T blank2 blank3 Home ↑ PgUp _ Y U I O P Esc"
        - "Menu s_{ A S D F G blank & ← blank3 → # blank H J K L s_} Del"
        - "Shift_L preferences Z X C V B blank3 End ↓ PgDn ↑ B N M ! ? BackSpace"
        - "show_actions Ctrl Alt space s_[ s_] s_> blank3 http com ← ↓ → space ; ' Return"
    actions:
        - "Tab F1  F2  F3  F4  F5  F6  F7  F8  F9  F10  F11  F12 M1 M2 M3 M4 Esc"
        - "Menu ! @ # $ % ^ & * ( ) ~ blank3 M5 M6 M7 M8 Del"
        - "blank3 1 2 3 4 5 6 7 8 9 0 ↑ blank3 M9 M10 M11 M12 BackSpace"
        - "show_letters Ctrl Alt space blank3 Up Left Down Right ← ↓ → space http com Return"
        
buttons:
    Shift_L:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "altline"
        icon: "key-shift"
    BackSpace:
        outline: "altline"
        icon: "edit-clear-symbolic"
        action: erase
    preferences:
        action: "show_prefs"
        outline: "special"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "wide"
        label: "123"
    show_numbers_from_symbols:
        action:
            set_view: "numbers"
        outline: "altline"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "small"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "small"
        label: "SYB"
    show_actions:
        action:
            set_view: "actions"
        outline: "small"
        label: "ACT"
    period:
        outline: "default"
        text: "."
    space:
        outline: "spaceline"
        text: " "
    blank:
        outline: "def_13"
        text: ""
    blank2:
        outline: "def_23"
        text: ""
    blank3:
        outline: "default"
        text: ""
    Return:
        outline: "wide"
        icon: "key-enter"
        keysym: "Return"
    s_|:
        outline: "def_23"
        text: "|"
    s_(:
        outline: "def_23"
        text: "("
    s_):
        outline: "def_23"
        text: ")"
    s_/:
        outline: "def_23"
        text: "/"
    s_b:
        outline: "def_23"
        text: "\\"
    s_{:
        outline: "def_23"
        text: "{"
    s_}:
        outline: "def_23"
        text: "}"
    s_[:
        outline: "def_23"
        text: "["
    s_]:
        outline: "def_23"
        text: "]"
    s_<:
        outline: "def_23"
        text: "<"
    s_>:
        outline: "def_23"
        text: ">"
    colon:
        text: ":"
    M1:
        outline: "small"
        text: "Heading Home"
        label: "Head"
    M2:
        outline: "small"
        text: "M2"
        label: "M2"
    M3:
        outline: "small"
        text: "OK, Thank You!"
        label: "OK,"
    M4:
        outline: "small"
        text: "M4"
        label: "M4"
    M5:
        outline: "small"
        text: "M5"
        label: "M5"
    M6:
        outline: "small"
        text: "M6"
        label: "M6"
    M7:
        outline: "small"
        text: "M7"
        label: "M7"
    M8:
        outline: "small"
        text: "M8"
        label: "M8"
    M9:
        outline: "small"
        text: "M9"
        label: "M9"
    M10:
        outline: "small"
        text: "M10"
        label: "M10"
    M11:
        outline: "small"
        text: "M11"
        label: "M11"
    M12:
        outline: "small"
        text: "M12"
        label: "M12"
    http:
        outline: "small"
        text: "https://"
        label: "http" 
    com:
        outline: "small"
        text: ".com"
        label: ".com"
    F1:
        outline: "small"
        keysym: "F1"
    F2:
        outline: "small"
        keysym: "F2"
    F3:
        outline: "small"
        keysym: "F3"
    F4:
        outline: "small"
        keysym: "F4"
    F5:
        outline: "small"
        keysym: "F5"
    F6:
        outline: "small"
        keysym: "F6"
    F7:
        outline: "small"
        keysym: "F7"
    F8:
        outline: "small"
        keysym: "F8"
    F9:
        outline: "small"
        keysym: "F9"
    F10:
        outline: "small"
        keysym: "F10"
    F11:
        outline: "small"
        keysym: "F11"
    F12:
        outline: "small"
        keysym: "F12"
    Esc:
        outline: "small"
        keysym: "Escape"
    Tab:
        outline: "small"
        keysym: "Tab"
    Del:
        outline: "small"
        keysym: "Delete"
    Insert:
        outline: "small"
        keysym: "Insert"
    Menu:
        outline: "small"
        keysym: "Menu"
    Pause:
        outline: "action"
        keysym: "Pause"
    Break:
        outline: "small"
        keysym: "Break"
    Home:
        outline: "small"
        keysym: "Home"
    End:
        outline: "small"
        keysym: "End"
    PgUp:
        outline: "small"
        keysym: "Page_Up"
    PgDn:
        outline: "small"
        keysym: "Page_Down"
    "↑":
        outline: "default"
        keysym: "Up"
    "↓":
        outline: "default"
        keysym: "Down"
    "←":
        outline: "default"
        keysym: "Left"
    "→":
        outline: "default"
        keysym: "Right"
    Up:
        label: "↑"
        outline: "action"
        keysym: "Up"
    Left:
        label: "←"
        outline: "action"
        keysym: "Left"
    Down:
        label: "↓"
        outline: "action"
        keysym: "Down"
    Right:
        label: "→"
        outline: "action"
        keysym: "Right"
    Ctrl:
        modifier: "Control"
        outline: "small"
        label: "Ctrl"
    Alt:
        modifier: "Alt"
        outline: "small"
        label: "Alt"
